image: node:latest

stages:
  - install
  - lint
  - build

cache:
  paths:
    - build/
    - node_modules/
    - .yarn-cache/

.changes: &changes
  - src/**/*
  - package.json
  - tsconfig.json
  - webpack.config.js
  - .gitlab-ci.yml
  - .prettier*

yarn_install:
  stage: install
  rules: [changes: *changes]
  script:
    - yarn --frozen-lockfile --check-files --cache-folder .yarn-cache install

lint:
  stage: lint
  rules: [changes: *changes]
  script:
    - yarn lint --check

test_build:
  stage: build
  rules: [changes: *changes]
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn build
